const statusCodes = {
  // 1xx Informational
  100: "Continue - The server has received the request headers and the client should proceed to send the request body.",
  101: "Switching Protocols - The requester has asked the server to switch protocols and the server has agreed to do so.",
  102: "Processing - The server has received and is processing the request, but no response is available yet.",
  103: "Early Hints - Used to return some response headers before final HTTP message.",

  // 2xx Success
  200: "OK - The request was successful.",
  201: "Created - A new resource was successfully created.",
  202: "Accepted - The request has been accepted for processing, but the processing has not been completed.",
  203: "Non-Authoritative Information - The returned information is from a cached copy instead of the origin server.",
  204: "No Content - The request was successful, but there's no content to return.",
  205: "Reset Content - The server has fulfilled the request and desires that the user agent reset the document view.",
  206: "Partial Content - The server is delivering only part of the resource due to a range header sent by the client.",
  207: "Multi-Status - The message body that follows is an XML message and can contain multiple separate response codes.",
  208: "Already Reported - The members of a DAV binding have already been enumerated in a previous reply.",
  226: "IM Used - The server has fulfilled a request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.",

  // 3xx Redirection
  300: "Multiple Choices - The request has more than one possible response.",
  301: "Moved Permanently - The URL of the requested resource has been changed permanently.",
  302: "Found - The URI of requested resource has been changed temporarily.",
  303: "See Other - The response to the request can be found under another URI using a GET method.",
  304: "Not Modified - The resource has not been modified since the last request.",
  305: "Use Proxy - The requested resource is available only through a proxy.",
  307: "Temporary Redirect - The request should be repeated with another URI, but future requests should still use the original URI.",
  308: "Permanent Redirect - The request and all future requests should be repeated using another URI.",

  // 4xx Client Errors
  400: "Bad Request - The request could not be understood.",
  401: "Unauthorized - Authentication is required.",
  402: "Payment Required - Payment is required for the requested resource.",
  403: "Forbidden - The server understood the request but refuses to authorize it.",
  404: "Not Found - The requested resource does not exist.",
  405: "Method Not Allowed - The request method is not supported for the requested resource.",
  406: "Not Acceptable - The requested resource cannot generate content according to the Accept headers sent.",
  407: "Proxy Authentication Required - The client must first authenticate itself with the proxy.",
  408: "Request Timeout - The server timed out waiting for the request.",
  409: "Conflict - The request could not be completed due to a conflict with the current state of the resource.",
  410: "Gone - The requested resource is no longer available and will not be available again.",
  411: "Length Required - The request did not specify the length of its content.",
  412: "Precondition Failed - The server does not meet one of the preconditions specified in the request.",
  413: "Payload Too Large - The request entity is larger than limits defined by server.",
  414: "URI Too Long - The URI provided was too long for the server to process.",
  415: "Unsupported Media Type - The request entity has a media type which the server or resource does not support.",
  416: "Range Not Satisfiable - The client has asked for a portion of the file, but the server cannot supply that portion.",
  417: "Expectation Failed - The server cannot meet the requirements of the Expect request-header field.",
  418: "I'm a teapot - The server refuses the attempt to brew coffee with a teapot.",
  421: "Misdirected Request - The request was directed at a server that is not able to produce a response.",
  422: "Unprocessable Entity - The request was well-formed but was unable to be followed due to semantic errors.",
  423: "Locked - The resource that is being accessed is locked.",
  424: "Failed Dependency - The request failed due to failure of a previous request.",
  425: "Too Early - The server is unwilling to risk processing a request that might be replayed.",
  426: "Upgrade Required - The client should switch to a different protocol.",
  428: "Precondition Required - The origin server requires the request to be conditional.",
  429: "Too Many Requests - The user has sent too many requests in a given amount of time.",
  431: "Request Header Fields Too Large - The server is unwilling to process the request because its header fields are too large.",
  451: "Unavailable For Legal Reasons - The resource is unavailable due to legal reasons.",

  // 5xx Server Errors
  500: "Internal Server Error - A generic error message for server issues.",
  501: "Not Implemented - The server does not support the functionality required to fulfill the request.",
  502: "Bad Gateway - The server was acting as a gateway or proxy and received an invalid response from the upstream server.",
  503: "Service Unavailable - The server is temporarily unavailable.",
  504: "Gateway Timeout - The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.",
  505: "HTTP Version Not Supported - The server does not support the HTTP protocol version used in the request.",
  506: "Variant Also Negotiates - The server has an internal configuration error.",
  507: "Insufficient Storage - The server is unable to store the representation needed to complete the request.",
  508: "Loop Detected - The server detected an infinite loop while processing the request.",
  510: "Not Extended - Further extensions to the request are required for the server to fulfill it.",
  511: "Network Authentication Required - The client needs to authenticate to gain network access.",
};

export default statusCodes;
